{
  "openapi": "3.0.3",
  "info": {
    "title": "Gradbuddy backend API",
    "version": "1.0.0",
    "description": "Access Gradbuddy users, scholarships, schools and other resources via API",
    "contact": {
      "name": "Sani Abubakar Adam",
      "url": "https://github.com/thernee"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Development server"
    }
  ],
  "security": [
    {
      "BearerAuth": []
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "summary": "Get all users",
        "description": "Fetch all user data from the database",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": [
                  {
                    "user_id": "123e4567-e89b-12d3-a456-426655441234",
                    "fullname": "Sani Abubakar Adam",
                    "email": "saniadam@me.com",
                    "username": "saniadam",
                    "hashed_password": "$2b$10$DqzQqQpXsZ7NqVQXcVH0G.0DxJ2EwvX4jXZqz6n5h9v0u2W9si",
                    "nationality": "Nigerian"
                  },
                  {
                    "user_id": "123e4567-e89b-12d3-a456-t7e89b12d3a456",
                    "fullname": "Magaret Mary",
                    "email": "magaret@me.com",
                    "username": "magaret",
                    "hashed_password": "$2b$10$DqzQqQpXsZ7NqVQXcVH0G-0yerdcvX4jXZqz6n5h9v6hdhdu2gr",
                    "nationality": "Angola"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "Users not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "summary": "Get user by id",
        "description": "Fetch a registered user data from the database",
        "operationId": "getUser",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123e4567-e89b-12d3-a456-426655441234"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "user_id": "123e4567-e89b-12d3-a456-426655441234",
                  "fullname": "Sani Abubakar Adam",
                  "email": "saniadam@me.com",
                  "username": "saniadam",
                  "hashed_password": "$2b$10$DqzQqQpXsZ7NqVQXcVH0G.0DxJ2EwvX4jXZqz6n5h9v0u2W9si",
                  "nationality": "Nigeria"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "User not found"
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update user",
        "description": "Update a registered user data in the database",
        "operationId": "updateUser",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123e4567-e89b-12d3-a456-426655441234"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "fullname": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  },
                  "hashed_password": {
                    "type": "string"
                  },
                  "nationality": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "User profile updated successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "User not found"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete user",
        "description": "Delete a registered user data from the database",
        "operationId": "deleteUser",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123e4567-e89b-12d3-a456-426655441234"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "User deleted successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "User not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/updatePassword/{user_id}": {
      "put": {
        "summary": "Update user password",
        "description": "Update a registered user password in the database",
        "operationId": "updateUserPassword",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123e4567-e89b-12d3-a456-426655441234"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "hashed_password": {
                    "type": "string"
                  },
                  "confirm_password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "User password updated successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "User not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "summary": "Register user",
        "description": "Register a new user in the database",
        "operationId": "registerUser",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "fullname": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  },
                  "hashed_password": {
                    "type": "string"
                  },
                  "nationality": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "User registered successfully"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "Invalid request payload"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "User already exists"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Login user",
        "description": "Login a registered user in the database",
        "operationId": "loginUser",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "hashed_password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "User logged in successfully"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "Invalid username or password"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "User not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/logout": {
      "post": {
        "summary": "Logout user",
        "description": "Logout a registered user in the database",
        "operationId": "logoutUser",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "User logged out successfully"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "Invalid token"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "success": false,
                    "message": "User not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/schools": {
      "get": {
        "summary": "Get all schools",
        "description": "Fetch all school data from the database",
        "operationId": "getAllSchools",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "school_id": {
                        "type": "integer"
                      },
                      "school_name": {
                        "type": "string"
                      },
                      "state": {
                        "type": "string"
                      },
                      "city": {
                        "type": "string"
                      },
                      "institutionalControl": {
                        "type": "string"
                      },
                      "rank": {
                        "type": "integer"
                      },
                      "acceptanceRate": {
                        "type": "number"
                      },
                      "schoolWebsite": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "school_id": 23,
                    "school_name": "Albert Einstein School",
                    "state": "Lagos",
                    "city": "Ikeja",
                    "institutionalControl": "Private",
                    "rank": 354,
                    "acceptanceRate": 45.7,
                    "schoolWebsite": "https://www.albeinstein.com"
                  },
                  {
                    "school_id": 24,
                    "school_name": "Charles Darwin School",
                    "state": "Abuja",
                    "city": "Abuja",
                    "institutionalControl": "Public",
                    "rank": 354,
                    "acceptanceRate": 45.7,
                    "schoolWebsite": "https://www.charlesdarwin.com"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Schools not found"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create school",
        "description": "Create a new school in the database",
        "operationId": "createSchool",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "school_name": {
                    "type": "string"
                  },
                  "state": {
                    "type": "string"
                  },
                  "city": {
                    "type": "string"
                  },
                  "institutionalControl": {
                    "type": "string"
                  },
                  "rank": {
                    "type": "integer"
                  },
                  "acceptanceRate": {
                    "type": "number"
                  },
                  "schoolWebsite": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "School created successfully"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Invalid request body"
                }
              }
            }
          }
        }
      }
    },
    "/schools/{school_id}": {
      "get": {
        "summary": "Get school by id",
        "description": "Fetch a school data from the database",
        "operationId": "getSchoolById",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 23
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "school_id": 23,
                  "school_name": "Albert Einstein School",
                  "state": "Lagos",
                  "city": "Ikeja",
                  "institutionalControl": "Private",
                  "rank": 354,
                  "acceptanceRate": 45.7,
                  "schoolWebsite": "https://www.albeinstein.com"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "School not found"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update school",
        "description": "Update a school data in the database",
        "operationId": "updateSchool",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 231
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "school_name": {
                    "type": "string"
                  },
                  "state": {
                    "type": "string"
                  },
                  "city": {
                    "type": "string"
                  },
                  "institutionalControl": {
                    "type": "string"
                  },
                  "rank": {
                    "type": "integer"
                  },
                  "acceptanceRate": {
                    "type": "number"
                  },
                  "schoolWebsite": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "School updated successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "School not found"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete school",
        "description": "Delete a school data in the database",
        "operationId": "deleteSchool",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 537
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "School deleted successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "School not found"
                }
              }
            }
          }
        }
      }
    },
    "/criteria/{school_id}": {
      "get": {
        "summary": "Get criteria by school id",
        "description": "Fetch criteria data from the database",
        "operationId": "getCriteriaBySchoolId",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 23
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "criteria_id": {
                        "type": "integer"
                      },
                      "school_id": {
                        "type": "integer"
                      },
                      "graduateLevel": {
                        "type": "string"
                      },
                      "offersScholarship": {
                        "type": "boolean"
                      },
                      "requiresAppFee": {
                        "type": "boolean"
                      },
                      "requiresGre": {
                        "type": "boolean"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "criteria_id": 12,
                    "school_id": 23,
                    "graduateLevel": "Masters",
                    "offersScholarship": true,
                    "requiresAppFee": true,
                    "requiresGre": true
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "School not found"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create criteria",
        "description": "Create a new criteria for a school in the database",
        "operationId": "createCriteria",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 23
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "school_id": {
                    "type": "integer"
                  },
                  "graduateLevel": {
                    "type": "string"
                  },
                  "offersScholarship": {
                    "type": "boolean"
                  },
                  "requiresAppFee": {
                    "type": "boolean"
                  },
                  "requiresGre": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Criteria created successfully"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "School not found"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete criteria",
        "description": "Delete a criteria for a school in the database",
        "operationId": "deleteCriteria",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 230
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Criteria deleted successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Criteria not found for given school id"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update criteria",
        "description": "Update a criteria for a school in the database",
        "operationId": "updateCriteria",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 230
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "school_id": {
                    "type": "integer"
                  },
                  "graduateLevel": {
                    "type": "string"
                  },
                  "offersScholarship": {
                    "type": "boolean"
                  },
                  "requiresAppFee": {
                    "type": "boolean"
                  },
                  "requiresGre": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Criteria updated successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Criteria not found for given school id"
                }
              }
            }
          }
        }
      }
    },
    "/favorites/{user_id}": {
      "get": {
        "summary": "Get favorites",
        "description": "Fetch favorite data from the database",
        "operationId": "getFavorites",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123e4567-e89b-12d3-a456-426655441234"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": [
                  {
                    "user_id": "123e4567-e89b-12d3-a456-426655441234",
                    "school_id": 1235
                  },
                  {
                    "user_id": "123e4567-e89b-12d3-a456-t7e89b12d3a456",
                    "school_id": 1175
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Favorites not found"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create favorite",
        "description": "Create a new favorite for a user in the database",
        "operationId": "createFavorite",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123e4567-e89b-12d3-a456-426655441234"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_id": {
                    "type": "integer"
                  },
                  "school_id": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Favorite created successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "User or school not found"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete favorite",
        "description": "Delete a favorite for a user in the database",
        "operationId": "deleteFavorite",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123e4567-e89b-12d3-a456-426655441234"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Favorite deleted successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Favorite not found for given user id"
                }
              }
            }
          }
        }
      }
    },
    "/scholarships": {
      "get": {
        "summary": "Get all scholarships",
        "description": "Fetch all scholarship data from the database",
        "operationId": "getScholarships",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": [
                  {
                    "school_id": 1753,
                    "scholarship_id": 1000,
                    "scholarship_name": "National Merit Scholarship",
                    "scholarship_description": "Scholarship for physics and chemistry students",
                    "program": "Physics and Chemistry",
                    "degree_level": "PhD"
                  },
                  {
                    "school_id": 1005,
                    "scholarship_id": 1001,
                    "scholarship_name": "Erasmus Mundus Scholarship",
                    "scholarship_description": "Scholarship for masters and phd students",
                    "program": "Computer science, Biology and Physics",
                    "degree_level": "Master and PhD"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Scholarships not found"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create scholarship",
        "description": "Create a new scholarship in the database",
        "operationId": "createScholarship",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "school_id": {
                    "type": "integer"
                  },
                  "scholarship_id": {
                    "type": "integer"
                  },
                  "scholarship_name": {
                    "type": "string"
                  },
                  "scholarship_description": {
                    "type": "string"
                  },
                  "program": {
                    "type": "string"
                  },
                  "degree_level": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Scholarship created successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "School not found"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete scholarship",
        "description": "Delete all scholarship in the database",
        "operationId": "deleteScholarships",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Scholarships deleted successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Scholarships not found"
                }
              }
            }
          }
        }
      }
    },
    "/scholarships/{school_id}": {
      "get": {
        "summary": "Get all scholarships by school id",
        "description": "Fetch all scholarship data from the database",
        "operationId": "getScholarshipsBySchoolId",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1753
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": [
                  {
                    "school_id": 1753,
                    "scholarship_id": 1000,
                    "scholarship_name": "National Merit Scholarship",
                    "scholarship_description": "Fellowship for physics and chemistry students",
                    "program": "Physics and Chemistry",
                    "degree_level": "PhD"
                  },
                  {
                    "school_id": 1005,
                    "scholarship_id": 1001,
                    "scholarship_name": "Erasmus Mundus Fellowship",
                    "scholarship_description": "Fellowship for masters and phd students",
                    "program": "Computer science, Biology and Physics",
                    "degree_level": "Master and PhD"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Scholarships not found for given school"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete all scholarships for a school",
        "description": "Delete all scholarship for a school in the database regardless of id",
        "operationId": "deleteScholarshipsBySchoolId",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1753
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "All scholarships deleted successfully for given school"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Scholarships not found for given school"
                }
              }
            }
          }
        }
      }
    },
    "/scholarships/{school_id}/{scholarship_id}": {
      "delete": {
        "summary": "Delete scholarship",
        "description": "Delete a scholarship for a school in the database",
        "operationId": "deleteScholarship",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1753
          },
          {
            "name": "scholarship_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1000
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Scholarship deleted successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Scholarship not found for given school"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update scholarship",
        "description": "Update a scholarship for a school in the database",
        "operationId": "updateScholarship",
        "parameters": [
          {
            "name": "school_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1753
          },
          {
            "name": "scholarship_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1000
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "school_id": {
                    "type": "integer"
                  },
                  "scholarship_id": {
                    "type": "integer"
                  },
                  "scholarship_name": {
                    "type": "string"
                  },
                  "scholarship_description": {
                    "type": "string"
                  },
                  "program": {
                    "type": "string"
                  },
                  "degree_level": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Scholarship updated successfully"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Scholarship not found for given school"
                }
              }
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "summary": "Search schools based on criteria",
        "description": "Search schools based on criteria like name, state, city, rank, acceptance rate, and more",
        "operationId": "searchSchool",
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "schema": {
              "type": "string"
            },
            "description": "Approximate name of the school"
          },
          {
            "in": "query",
            "name": "state",
            "schema": {
              "type": "string"
            },
            "description": "State the school is located in"
          },
          {
            "in": "query",
            "name": "city",
            "schema": {
              "type": "string"
            },
            "description": "City the school is located in"
          },
          {
            "in": "query",
            "name": "rank",
            "schema": {
              "type": "integer"
            },
            "description": "Rank of the school"
          },
          {
            "in": "query",
            "name": "acceptance_rate",
            "schema": {
              "type": "number"
            },
            "description": "Acceptance rate of the school"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": [
                  {
                    "name": "MIT",
                    "state": "MA",
                    "city": "Boston",
                    "rank": 1,
                    "acceptance_rate": 10.8,
                    "school_website": "https://www.mit.edu"
                  },
                  {
                    "name": "Stanford",
                    "state": "CA",
                    "city": "Stanford",
                    "rank": 10,
                    "acceptance_rate": 45.7,
                    "school_website": "https://www.stanford.edu"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": false,
                  "message": "Schools not found"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Bearer Authentication using JWT"
      }
    }
  }
}